import test from 'node:test';import assert from 'node:assert/strict';
import {GenericLumiV2Adapter,prepareGenericV2Episode,genericWorkerReadiness} from '../lib/lumi-generic-v2-adapter.js';
import {genericFixture} from './fixtures/generic-v2.js';
import {PROFILE_SHA} from '../lib/lumi-production-profile-v2.js';
test('generic fictitious episodes route plan/scene/Director/journal/QA/audio/master without third-short identifiers',async()=>{
 for(const episodeId of ['ep_fiction_alpha','ep_fiction_beta']){const f=await genericFixture(episodeId);try{const prepared=prepareGenericV2Episode(f.request);assert.equal(prepared.episode_id,episodeId);assert.ok(prepared.actions.every(a=>!a.key.match(/q3[1-6]/)));await f.adapter.create({user:'fixture',request:f.request,authorizedCeilingUsd:1});while((await f.store.getEpisode(episodeId)).first_pending_action)await f.adapter.resume({episodeId});assert.equal(f.simulatedEmissions(),19);assert.equal(f.journal.rows.size,19);assert.equal(f.trace.at(-1),'MASTER_REVIEW');assert.ok(f.trace.includes('TTS_STORAGE'));assert.ok(f.trace.includes('CAPTIONS'));assert.equal((await f.store.getEpisode(episodeId)).runner_enabled,false);}finally{await f.cleanup();}}
});
test('missing concrete workers block before creating a checkpoint; live routing requires activation',async()=>{const f=await genericFixture();try{const a=new GenericLumiV2Adapter({manager:f.manager,journal:f.journal,simulation:true});await assert.rejects(a.create({request:f.request}),/WORKER_BINDINGS/);assert.equal(await f.store.getEpisode(f.request.episodePlan.episode.id),null);assert.equal(genericWorkerReadiness().status,'BLOCKED');const live=new GenericLumiV2Adapter({manager:f.manager,journal:f.journal,workers:f.workers});await assert.rejects(live.create({request:f.request}),/ACTIVATION/);assert.equal(f.simulatedEmissions(),0);}finally{await f.cleanup();}});
test('immutable inputs, frozen profiles and complete scene coverage are enforced',async()=>{const f=await genericFixture();try{assert.throws(()=>prepareGenericV2Episode({...f.request,shotPlans:f.request.shotPlans.slice(1)}),/PEDAGOGICAL/);assert.throws(()=>prepareGenericV2Episode({...f.request,characterProfile:{id:'other',source_sha:'a'.repeat(64)}}),/FROZEN/);await f.adapter.create({request:f.request,authorizedCeilingUsd:1});const changed=structuredClone(f.request);changed.episodePlan.episode.title='Changed';await assert.rejects(f.adapter.create({request:changed}),/IMMUTABLE/);}finally{await f.cleanup();}});
test('restart at a claimed stage never redispatches; failed TTS storage pauses safely',async()=>{const f=await genericFixture();try{const id=f.request.episodePlan.episode.id;await f.adapter.create({request:f.request,authorizedCeilingUsd:1});await f.manager.checkpoint(id,s=>{s.actions[0].dispatch_state='DISPATCHING';});await assert.rejects(f.adapter.resume({episodeId:id}),/RECONCILIATION/);assert.equal(f.simulatedEmissions(),0);await f.manager.checkpoint(id,s=>{s.actions[0].dispatch_state='NOT_DISPATCHED';for(const a of s.actions){if(a.key==='tts_storage')break;a.evidence={provider_succeeded:true,artifact_persisted:true,sha_verified:true,artifact_verified:true};a.status='COMPLETE';}});f.workers.TTS_STORAGE.run=async()=>{throw Error('storage unavailable');};await assert.rejects(f.adapter.resume({episodeId:id}));const state=await f.store.getEpisode(id),incident=await f.store.getIncident(state.active_incident_id);assert.equal(incident.error_class,'TTS_STORAGE_FAILURE');assert.equal(state.runner_enabled,false);}finally{await f.cleanup();}});
