import test from 'node:test';import assert from 'node:assert/strict';
import {newSession,MemoryReviewStore,ReviewService,sha256,renderTelegramPanel,artifactReview,reviewKey} from '../lib/telegram-review-v1/core.js';
import {MakeTransport,acknowledgeCommand} from '../lib/telegram-review-v1/make-transport.js';
import {HOME_ASSET,loadOwnedHomeAsset} from '../lib/telegram-review-v1/home-asset.js';
const bytes=Buffer.from('SYNTHETIC_VIDEO_NOT_PLAYABLE'),coverBytes=Buffer.from('SYNTHETIC_PHOTO_NOT_PLAYABLE');
const master={artifact_id:'fixture-master',sha256:sha256(bytes),mime:'video/mp4',size:bytes.length,bucket:'fixture',path:'master.mp4',width:1080,height:1920,duration:4};
const cover={...master,artifact_id:'fixture-home',sha256:sha256(coverBytes),mime:'image/png',size:coverBytes.length,path:'home.png'};
async function setup({approved=false}={}){
 const store=new MemoryReviewStore(),session=newSession({user_id:'1',chat_id:'1',message_id:138,cover,legacy_menu:[[{text:'Ideas',callback_data:'ideas'}]]});
 session.panel_content_type='video';session.home_restore_capability={media_to_text:false};session.deliveries[master.sha256]={telegram_file_id:'MASTER_FILE',telegram_file_unique_id:'MASTER_UNIQUE'};
 await store.create('1',session);const uploads={master:0,home:0};const svc=new ReviewService({store,telegram:new MakeTransport(),loadBytes:async a=>{uploads[a.sha256===cover.sha256?'home':'master']++;return a.sha256===cover.sha256?coverBytes:bytes;}});
 await svc.registerEpisode('1','1',{episode_id:'ep',title:'Fixture',review_mode:'SUPERVISED',beats:9,master,shots:[{shot_id:'generic-shot',artifact:master,technical_qa:'PASS',creative_qa:'PASS'}]});
 if(approved){const r=await store.get('1'),e=r.state.episodes.ep,key=reviewKey('ep',null,master.sha256);e.reviews={[key]:{episode_id:'ep',artifact_sha:master.sha256,shot_id:null,status:'APPROVED',human_status:'MASTER_HUMAN_APPROVED',review_version:1}};e.review_versions={[key]:1};await store.cas('1',r.revision,r.state);}
 const message=c=>({chat:{id:1},message_id:138,caption:c.body.media.caption,reply_markup:c.body.reply_markup,...(c.body.media.type==='photo'?{photo:[{file_id:'HOME_FILE',file_unique_id:'HOME_UNIQUE'}]}:{video:{file_id:'MASTER_FILE',file_unique_id:'MASTER_UNIQUE',file_size:bytes.length}})});
 const ack=c=>acknowledgeCommand(store,'1','1',c.idempotency_key,message(c));
 const show=async screen=>{const r=await svc.show('1','1',screen),c=r.commands[0];assert.equal(c.method,'editMessageMedia');assert.equal(c.message_id,138);assert.ok(c.body.reply_markup.inline_keyboard.length);await ack(c);return c;};
 const cb=async(c,action)=>{const s=(await store.get('1')).state,[token]=Object.entries(s.tokens).reverse().find(([,v])=>v.action===action);const r=await svc.callback({id:'SYNTHETIC_CALLBACK_'+action,from:{id:1},message:message(c),data:'lr:'+token});if(r.commands)await ack(r.commands[0]);return r;};
 return {store,svc,ack,show,cb,message,uploads};
}
const transitions=[['VIDEO → HOME PHOTO','master','menu','photo'],['HOME PHOTO → VIDEO','menu','master','video'],['VIDEO → DETAILS PHOTO','master','details','photo'],['DETAILS PHOTO → VIDEO','details','master','video'],['VIDEO → APPROVED PHOTO','master','master_approved','photo'],['APPROVED PHOTO → HOME PHOTO','master_approved','menu','photo'],['HOME → PROGRESS PHOTO','menu','progress','photo'],['PROGRESS → SHOT VIDEO','progress','shot','video'],['SHOT VIDEO → HOME PHOTO','shot','menu','photo']];
for(const [name,from,to,type]of transitions)test(name+' preserves full panel 138',async()=>{const f=await setup({approved:true});await f.show({kind:from,episode_id:'ep'});const c=await f.show({kind:to,episode_id:'ep'});assert.equal(c.body.media.type,type);assert.match(c.body.media.caption,/./);assert.equal(f.uploads.master,0);assert.ok(f.uploads.home<=1);});
test('HOME registers once and both file_ids survive navigation/restart',async()=>{const f=await setup();for(const kind of ['menu','master','menu','master','menu'])await f.show({kind,episode_id:'ep'});const svc=new ReviewService({store:f.store,telegram:new MakeTransport(),loadBytes:()=>{throw Error('reupload forbidden');}});const c=(await svc.show('1','1',{kind:'master',episode_id:'ep'})).commands[0];assert.equal(c.upload_required,false);await f.ack(c);assert.deepEqual(f.uploads,{master:0,home:1});const s=(await f.store.get('1')).state;assert.equal(s.TELEGRAM_HOME_FILE_ID,'HOME_FILE');assert.equal(s.HOME_ASSET_SHA,cover.sha256);assert.equal(s.deliveries[master.sha256].telegram_file_id,'MASTER_FILE');});
test('approval renders PHOTO success, remains idempotent and does not publish',async()=>{const f=await setup(),c=await f.show({kind:'master',episode_id:'ep'}),s=(await f.store.get('1')).state,[token]=Object.entries(s.tokens).find(([,v])=>v.action==='approve_final');const cb={id:'SYNTHETIC_APPROVAL',from:{id:1},message:f.message(c),data:'lr:'+token};for(let i=0;i<2;i++){const r=await f.svc.callback(cb);assert.equal(r.commands[0].body.media.type,'photo');assert.match(r.commands[0].body.media.caption,/Video aprobado/);await f.ack(r.commands[0]);}const n=(await f.store.get('1')).state;assert.equal(n.reviews.length,1);assert.equal(n.episodes.ep.MASTER_HUMAN_APPROVED,true);assert.equal(artifactReview(n.episodes.ep,master).review_version,1);assert.equal(f.uploads.master,0);});
test('BACK restores master then episode then HOME from persisted stack',async()=>{const f=await setup();await f.show({kind:'menu'});const progress=await f.show({kind:'progress',episode_id:'ep'}),video=await f.show({kind:'master',episode_id:'ep'}),details=(await f.cb(video,'details')).commands[0];assert.equal(details.body.media.type,'photo');const b=(await f.cb(details,'back')).commands[0];assert.equal(b.body.media.type,'video');assert.equal(b.body.media.caption,video.body.media.caption);assert.deepEqual(b.body.reply_markup.inline_keyboard.map(r=>r.map(b=>b.text)),video.body.reply_markup.inline_keyboard.map(r=>r.map(b=>b.text)));const e=(await f.cb(b,'back')).commands[0];assert.equal(e.body.media.caption,progress.body.media.caption);await f.cb(e,'menu');assert.deepEqual((await f.store.get('1')).state.navigation_stack,[]);});
test('INCIDENT BACK restores complete progress',async()=>{const f=await setup(),p=await f.show({kind:'progress',episode_id:'ep'}),c=await f.show({kind:'incident',episode_id:'ep'}),b=(await f.cb(c,'back')).commands[0];assert.equal(b.body.media.caption,p.body.media.caption);assert.equal(b.body.media.type,'photo');});
test('photo acknowledgement rejects residual video, wrong keyboard and binding',async()=>{const f=await setup(),c=(await f.svc.show('1','1',{kind:'menu'})).commands[0];await assert.rejects(acknowledgeCommand(f.store,'1','1',c.idempotency_key,{...f.message(c),video:{file_id:'old'}}),/media_type/);await assert.rejects(acknowledgeCommand(f.store,'1','1',c.idempotency_key,{...f.message(c),reply_markup:{inline_keyboard:[]}}),/keyboard/);await f.ack(c);const n=(await f.svc.show('1','1',{kind:'menu'})).commands[0];await assert.rejects(acknowledgeCommand(f.store,'1','1',n.idempotency_key,{...f.message(n),photo:[{file_id:'wrong',file_unique_id:'WRONG'}]}),/binding/);await f.ack(n);});
test('renderer exposes atomic fields and refuses a video HOME cover',async()=>{const f=await setup(),s=(await f.store.get('1')).state,v=renderTelegramPanel(s,{kind:'menu'});for(const k of ['media_type','media_file_id','caption','inline_keyboard','state_id','review_version','artifact_binding'])assert.ok(k in v,k);assert.throws(()=>renderTelegramPanel({...s,cover:master},{kind:'menu'}),/HOME_PHOTO/);});
test('owned HOME asset has exact bytes and forbids arbitrary files',async()=>{assert.equal(sha256(await loadOwnedHomeAsset(HOME_ASSET)),HOME_ASSET.sha256);await assert.rejects(loadOwnedHomeAsset({...HOME_ASSET,path:'server.js'}),/binding/);});
test('publication panels are media-backed with confirmation closed',async()=>{const f=await setup({approved:true});for(const kind of ['publish','publish_select','publish_preview','publish_confirm','publishing','published','publish_error'])assert.equal((await f.show({kind,episode_id:'ep'})).body.media.type,'photo');const c=await f.show({kind:'publish_confirm',episode_id:'ep'}),before=await f.store.get('1');assert.equal((await f.cb(c,'publish_commit')).error,'PUBLICATION_DISABLED');assert.deepEqual(await f.store.get('1'),before);});
