create table if not exists public.social_connections (
  id bigint generated by default as identity primary key,
  channel_id bigint not null references public.channels(id) on delete cascade,
  platform text not null check (platform in ('youtube','instagram','tiktok','facebook')),
  account_id text,
  account_name text,
  credentials_ciphertext text not null,
  credentials_iv text not null,
  credentials_auth_tag text not null,
  status text not null default 'connected' check (status in ('pending','connected','expired','revoked','error')),
  connected_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (channel_id, platform)
);

alter table public.social_connections enable row level security;
revoke all on table public.social_connections from anon, authenticated;

drop trigger if exists trg_social_connections_updated_at on public.social_connections;
create trigger trg_social_connections_updated_at
before update on public.social_connections
for each row execute function public.set_updated_at();
